apiVersion: v1
kind: Service
metadata:
  name: sharelist
  annotations:
    dev.okteto.com/auto-ingress: "domain"
spec:
  type: ClusterIP  
  ports:
  - name: "sharelist"
    port: 33001
  selector:
    app: sharelist
